######################################################################################################################################
## SexyMotd Configuration File                                                                                                      ##
## Learn more about how to set up SexyMotd at http://qwertyness.com/index.php/portfolio/sexymotd                                    ##
##                                                                                                                                  ##
## When updating to a new version where the configuration file changes, you must reset the file to prevent errors.                  ##
## To do this:                                                                                                                      ##
## 1. Stop the server.                                                                                                              ##
## 2. Backup the configuration file and delete it from the plugin folder.                                                           ##
## 3. Restart the server.                                                                                                           ##
## 4. Copy and paste the desired settings back into the newly generated file. (As long as that section's syntax hasn't changed)     ##
######################################################################################################################################

# Add a new sub-entry for each separate Motd you want in the random pool.
# Examples below
motds:
  - '&6&lFACTIONMANIA &7(1.8.*)%newline%&eloja.factionmania.tk &7- Beta 1.0'

# The value to show as the maximum player limit to the server. DOES NOT CHANGE THE ACTUAL LIMIT.
maxPlayers:
  enabled: false
  maxPlayers: 1500

# The value to show as the amount of online players. A random entry is chosen from the list on each ping.
playerCount:
  enabled: false
  playerCount:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  
icon:
  # Sets the icon to the pinging player's head.
  # Using the avatar image could potentially have a drastic effect on response speed, depending on connection.  If your server has a slow connection, this is not recommended.
  enableAvatarIcon: false
  # Adds an overlay to the head image. Can be used independently from the avatar icon.
  enableOverlayImage: false
  imagePath: 'C:/Users/BillyBobJoe/Pictures/billyBobJoeIcon.jpg'

 #The text to display when hovering over the server in the server list.
playerMessage:
  enabled: true
  playerMessage:
  - '&6&lFACTIONMANIA &7(1.8.x)%newline%%newline%&eTeam Speak: &fts.factionmania.tk%newline%&eTwitter: &f@Faction_Mania%newline%&eLoja: &fwww.loja.factionmania.tk%newline%%newline%&6Entra e venha se divertir conosco'

# Replaces the online and max player counts with custom text.  Color codes and variables work with this.
fakeVersion:
  enabled: false
  fakeVersion: '&4Manutencao'

# The default name to display in place of %playername% when the ping's IP address isn't logged.
defaultPlayerName: 'FactionMania'

# Whether or not to log when a player pings and the connection is closed.
pingLogging: false

# Create custom variables here. Custom variables can be used like any of the default SexyMotdBungee variables.
# MAKE SURE to place apostrophes around all components of the custom variable as they are all read as String objects from the configuration.
variables:
  largeplayercount:
    variable: 'onlineplayers'
    operator: '>'
    condition: '10'
    value: '&aIts sure getting popular around %servername%!'
    negValue: '&cGotta step up that recruiting skill! %servername%'