name: EffectsHG
version: 1.0
author: ViitorGGamer
main: me.recenthg.Main
commands:
  iniciar:
  tempo:
  kit:
  kit2:
  bc:
  spawn:
  gm:
  fly:
  admin:
  chat:
  darcoins:
  tag:
  arenapvp:
  forcefeast:
  feast:
  pro:
  youtuber:
  jogadores:
  arena:
  fake:
  tfake:
  spec:
  jogo:
  tell:
  kick:
  pvp:
  vis:
  cc:
  unban:
  tp:
  sorteiokit:
  skit:
  ban:
  report:
  score:
  inv:
  coins:
  sc:
  desistir:
  clan:
