# Dinheiro que irá matando o Mob: #
skeleton: 10
creeper: 11
spider: 12
zombie: 13
slime: 14
ghast: 15
pigzombie: 16
enderman: 17
cavespider: 18
silverfish: 19
blaze: 20
magmacube: 21
bat: 22
witch: 23
pig: 24
sheep: 25
mushroomcow: 26
cow: 27
chicken: 28
squid: 29
wolf: 30
ocelot: 31
villager: 32
enderdragon: 33
wither: 34