Magnata: "SrD3ad"
Chat: "On"
MaxX: 5000
MaxZ: 5000
slime:
  divisao: false
  slimeball:
    drop:
      ativo: true
      minimo: 30
      maximo: 64
      chance: 50
    exp:
      ativo: true
      minimo: 10
      maximo: 15
      chance: 100
CorDoNome: '&a'
tpa-cooldown: 30
keep-alive: 60