TXT1: Voce Ganhou $
TXT2: Por Matar Um
ENABLE_ZOMBIE: true
ZOMBIE: 10.0
ENABLE_SPIDER: true
SPIDER: 10.0
ENABLE_SKELETON: true
SKELETON: 10.0
ENABLE_CREEPER: true
CREEPER: 15.0
ENABLE_BAT: true
BAT: 5.0
ENABLE_ENDERMAN: true
ENDERMAN: 50.0
ENABLE_PIGZOMBIE: true
PIGZOMBIE: 50.0
ENABLE_WOLF: true
WOLF: 50.0
ENABLE_BLAZE: true
BLAZE: 50.0
ENABLE_CAVESPIDER: true
CAVESPIDER: 25.0
ENABLE_GHAST: true
GHAST: 50.0
ENABLE_MAGMACUBE: true
MAGMACUBE: 50.0
ENABLE_SILVERFISH: true
SILVERFISH: 5.0
ENABLE_WITHERSKELETON: true
WITHERSKELETON: 25.0
ENABLE_SLIME: true
SLIME: 25.0
ENABLE_WITCH: true
WITCH: 25.0
ENABLE_GOLEM: true
GOLEM: 50.0
ENABLE_ENDERDRAGON: true
ENDERDRAGON: 1000000.0
ENABLE_WITHER: true
WITHER: 1000000.0
ENABLE_GIANT: true
GIANT: 1000.0
