TnT:
    name: '&c&lTNT &cde impulsão'
    lore:
    - ''
    - ' &6&lD&6escrição&7: Essa tnt especial'
    - '  &7quando colocada no chão e ativada,'
    - '  &7ela não destruirá os blocos próximos'
    - '  &7Mas cuidado ela também te da dano!'
    - ''
    glow: true