build-mode: false
chat-plugin: true
chat:
  chat-no-game: '%prefix%&7%player%: %message%'
  chat-game: '%prefix%&7%player%: %message%'
  chat-game-spectator: '&7[SPECTATOR] %prefix%&7%player%: %message%'
database:
  type: sqlite
  username: ratix
  password: cake
  hostname: localhost
  port: 3306
  database: skywars_data
game:
  coins-per-kill: 5
  coins-per-win: 30
globalSpawn: -2560.6394206932373;53.0;744.5739928220943;3.7235582;-89.82215;world
