##################################
## CONFIGURE STRINGS INVENTORY  ##
##################################
game-inventory:
 name: "&eGame Arena List"
 rows: 3
state-string:
 waiting: "&a&lWaiting"
 starting: "&6&lStarting"
inventory:
 waiting:
  name: "&a%name%" 
  item: "133"
  lore:
  - "&f"
  - "%gameState%"
  - "&7%alivep%/%maxp%"
  - "&f"
  - "&aClick to join!"
 starting:
  name: "&6%name%" 
  item: "41"
  lore:
  - "&f"
  - "%gameState%"
  - "&7%alivep%/%maxp%"
  - "&f"
  - "&aClick to join!"
 