##############################################
## FALSE = MULTI-ARENA SIGNS                ##
## TRUE = SYSTEM QUEUE GAMES (LIKE HYPIXEL) ##
##############################################
game-queue: true
########################################
## GAME-QUEUE IS TRUE SIGN GAME QUEUE ##
########################################
queue-behind-block: "159:9"
queue-lines:
 line1: "&a[JOIN]"
 line2: "&lSOLO"
 line3: "%gamesqueue% In Queue"
 line4: "&1Normal Mode"
##########################################
## GAME-QUEUE IS FALSE MULTIARENA LINES ##
##########################################
multiarena-state:
 waiting: "&2WAITING"
 starting: "&6STARTING"
 pregame: "&4PRE-GAME"
 game: "&4IN-GAME"
 ending: "&cENDING"
blocks:
  waiting: "159:9"
  starting: "159:9"
  game: "159:9"
  pregame: "159:9"
  ending: "159:9"
multiarena-lines:
 line1: "&a[JOIN]"
 line2: "%gameState%"
 line3: "&l%map%"
 line4: "%alivep%/%max%"