# JoinMessagePlus
#       
# EnableJoinMessage: true/false - Should the Join-Message be enabled.
# EnableQuitMessage: true/false - Should the Quit-Message be anabled.
# JoinMessage: '&6[&a+&6] %player' - Your custom Join-Message (%player will be replaced with the player's names).
# JoinMessage: '&6[&4-&6] %player' - Your custom Join-Message (%player will be replaced with the player's names).
#       
EnableJoinMessage: true
EnableQuitMessage: true
JoinMessage: '&1[&a+&f]&9 %player'
QuitMessage: '&1[&4-&f]&9 %player'
