autoBackup: false
backupDelayInHours: 24
maxBackupsBeforeErase: 4
lastBackup: 1485606824394
compressionLevel_1-10: 3
slowdownWhenServerLags: false
showSlowdownMessage: false
debug: false
name: backup_%time%
extension: rar
exemptFolders:
- example/this/folder/wont/backup
- example/folder
- example/file.yml
saveFolder: plugins/EasyBackup/Backups
allowInGameCommands: true
