#####################################
#             T_Reports             #
#          Versão: 1.0 - Beta       #
#           Author: THGPlay         #
#####################################

#  $player% jogador a ser reportado
#  DisplayName sera o nome que aparecerar no GUI de reports
DisplayName: '&e&l &f%player%'

# Lista de NOMES de ITENS no MINECRAFT: http://www.minecraftinfo.com/idnamelist.htm
# 
#             T_Reports             #
#          Versão: 1.0 - Beta       #
#           Author: THGPlay         #

#Itens que recebera após entrar no modo AdminReport
Item:
  Report:
    Item: COMPASS
    Nome: '&b&lReports'
    Slot: 1
  Punir:
    Item: PAPER
    Nome: '&5&lPunir'
    Slot: 4
  Sair:
    Item: REDSTONE_TORCH_ON
    Nome: '&c&lSair'
    Slot: 7
#Nome do Gui de Players Reportados
Menu:
  Nome: '&c&lReports'
#Tempo para poder reportar novamente em horas
Tempo:
  Report: 1
  Mensagem: '&cVocê so podera reportar novamente em: %tempo%'
#Mensagens do Plugin
Mensagens:
  SemPermissao: '&cVocê não tem permissão!'
  JogadorOffline: '&cJogador está off no momento'
  AtiveModoReport: '&cVocê precisa estar no modo &a&lAdminReport &cpara punir alguem!'
  ModoReport:
    Ativo: '&7Você entrou no modo &a&lAdminReport'
    Desativado: '&7Você saiu do modo &c&lAdminReport'
  Punindo:
  - ''
  - '&cPuna o jogador clicando nas mensagens:'
  - ''
  FormatoTemporario: '&aDigite o tempo usando o formato de: 10:20:30:40 no caso 10 dias 20 horas 30 minutos e 40 segundos'
Broadcast:
  Ativar: true
  Mensagem:
    Broadcast:
    - ''
    - '&c&lJOGADOR &f%player% &c&lFOI BANIDO'
    - '&6&lMOTIVO: &f%motivo%'
    - '&a&lTEMPO: &f%tempo%'
    - '&4&lSTAFFER: &f%admin%'
    - ''