DO NOT DELETE: PerWorldChatPlus is developed and managed by Shades161
Config Version: '4.0'
Check for Updates: true
Lang: En
Announce Dev Join: true
Prefix: '&5[PerWorldChat]'
Global:
  Prefix: '&4[Global]'
  Override: '!wc'
  Always Global: false
  TimedGlobal:
    Allow: true
    Announce: true
    DefaultTime: 5
    'On': false
Alert:
  Mention:
    OnName: true
    RequirePermission: false
    RequireAtSymbol: false
    SendNotice: false
SharesList:
- world
