# %player% = Player    %broke% = Player has broke blocks.    ; Split Command or Worlds
#How Many Blocks Does the player has to break to launch the command? (Loops)
Interval: 50
#Set Up Your Own Messages
Messages:
  MineMessage: '&cYou have broke &6%broke% &cblocks!'
  MessageActivated: false
#Command to be launched when player destroyes "Interval" Blocks Ammount. Use ; To Split The Command
Commands: ;kit sortudo %player% ;
#Reset on reach The interval So it will not go to 21..22.23..24 Because command will be not launched.
ResetOnReach: true
#Enabled Worlds Use ; To Split The Worlds
Enabled_Worlds: ;SPAWN;test1
