############################
#		Criador: Trow	   #
#		Version: 1.3       #
############################

#Configuracao de Permissao.
Permissao:
  Permissao_Membro: "tgpermission.usar"
  Sem_Permissao_Membro: "&cSem permissao."
  Permissao_Staff: "tgpermission.usar"
  Sem_Permissao_Staff: "&cSem permissao."
  
#Configuracao de reportar.
Reportar:
  Use_Report: "&cUse: &6/&6Reportar &0[&6Jogador&0] &0[&6Motivo&0]"
  Offline: "&cPlayer offline!"
  Ja_Reportou: "&6Voce Ja Tem Um Report Em Andamento."
  Erro: "&cVoce Nao Pode Reportar a Si Mesmo."
  Report:
    - '&6Staffs Que Receberam Esta Denuncia: &4{staffs}'
    - '&6Reportador: &2{reportador}'
    - '&6Reportado: &c{reportado}'
    - '&6ID: &f{id}'
    - '&6Motivo: &c{motivo}'
  Use_Responder: "&cUse: &6/Responder &0[&6Jogador&0] &0[&6Resposta&0]"
  Respondeu: "&aVoce Respondeu a Denuncia de: &6{player}"
  Nao_Reportou: "&cEste Jogador Nao Fez Nenhum Report."
  
#Configuracao Geral.
Geral:
  Ativar_Economia: false
  Custo: 0
  Sem_Dinheiro: "&6Voce Nao Tem Dinheiro Para Reportar. Voce Precisa De &2$ {custo}&6."
  