# Titlebar v1.3.1.11 by sn1cko
# Time is set in milliseconds which means every 20 = 1 second
# for example: 6000 = 5 minuntes OR 300 = 15 seconds
# 
# The announcer will never stop if the time is set to 0
# Else it will stop after the amount of milliseconds you wish
# 
# There are currently 15 variables available which can be built in
# for example %player% - will display the playername or %health% - will give out the health
# all other variables can be found on the website
# http://dev.bukkit.org/bukkit-plugins/titlebar/pages/variables
Titlebar:
  Settings:
    FirstJoin:
      Toggle: false
      Time: 5
      Titles:
      - ''
      Subtitles:
      - ''
    Join:
      Toggle: true
      Time: 25
      Titles:
      - '&e&lFactions SUN'
      Subtitles:
      - ''
    Time:
      Fade-In: 5
      Stay: 3
      Fade-Out: 1
    Staff:
      Permission: titlebar.staff
    ColorCodes:
      Toggle: true
    TitleMessage:
      Toggle: true
titlebar:
  Settings:
    ShowVanishedPlayerOnVariable:
      Toggle: false
      ChangeText:
        Toggle: false
        UsersSeeOnlineText: '%online%'
        StaffsSeeOnlineText: '%online% | %vanished%'
TitlebarAnnouncer:
  Settings:
    Toggle: false
    StopTime: 0
    Time: 6000
    Messages:
      Titles:
      - Ja criou sua fac? /f
      Subtitles:
      - '&e:)'
