Anuncio Mensagens:

#Coloque o nome do servidor ou qualquer outro nome.
Name: '&8[&a&lFenix&f&lPvP&8]'

#Configuraçoes do chat, edite do geito que desejar.
Formato: "&8[&aAnuncio&6Vip&8] &f{player}&a: &a{msg}"

#Edite todas as mensagens dos plugins.
Mensagem1: '&bUtilize: /anuncio <mensagem>'
Mensagem2: '&bVocê precisa de &e@quantidade &bcoins.'
Mensagem3: '&bApenas jogadores &6[VIP] &bpodem utilizar o Anuncio!'

#Coloque o Item que será utilizado para falar no chat. 
Quantidade: 500