name: ExtremePvP
version: 1.0
main: nobody.main.Main
author: NeeroRekt
description: Se você está lendo isso, sinta-se um fracassado.
commands:
  kit:
  kits:
  kill:
  tphere:
  tpall:
  ver:
  money:
  horas:
  kitpos1:
  kitpos2:
  kitpos3:
  kitpos4:
  kitpos5:
  sudo:
  topkills:
  rank:
  lojaitens:
  build:
  aplicar:
  villagerparkour:
  darkills:
  resouper:
  warpss:
  eventos:
  extra:
  xp:
  sonic:
  as:
  autosoup:
  comprarcaixa:
  caixa:
  doarcaixa:
  setparkour:
  parkour:
  gratis:
  score:
  kits:
  kits2:
  kit:
  kick:
  loja:
  fake:
  heads:
  lojas:
  lojaperms:
  warps:
  setcsgo:
  csgo:
  challenge:
  setchallenge:
  setfps:
  fps:
  setmain:
  main:
  setmlg:
  mlg:
  inferno:
  setinferno:
  ninja:
  setrdm:
  rdm:
  setfisherman:
  fishermano:
  tag:
  setarena:
  cc:
  check:
  sc:
  stomper:
  report:
  skit:
  tell:
  mutechat:
  danoglobal:
  bc:
  menu:
  headshot:
  spawn:
  setspawn:
  status:
  regras:
  tp:
  gm:
  admin:
  clicktest:
  broadcast:
  spiderman: