#--------------------------------------------------------------------#
#                   ClearLag Configuration File                      #
#--------------------------------------------------------------------#
# Configure to your liking, reload the config by tying: /lagg reload #
#                                -                                   #
#        Here is a helpful tutorial on this configuration setup!     #
#   http://dev.bukkit.org/server-mods/clearlagg/pages/config-setup/  #
#--------------------------------------------------------------------#
#                     All possible mob names                         #
# http://dev.bukkit.org/server-mods/clearlagg/pages/mob-types/nodes/ #
#--------------------------------------------------------------------#
settings:
  auto-update: false
  enable-signs: true
  config-version: six
  keep-spawn-in-memory: true
  
#This option reduces the explosions of mass amounts of tnt, and reduces tnt lag
tnt:
  tnt-reducer: false
  
#This option reduces fire spread rate
firespread-reducer:
  enabled: flase
  time: 450
  
#How many entities should one chunk be allowed to hold?
chunk-entity-limiter:
  enabled: false
  clean-chunk: true
  limit: 50
  
spawn-limiter:
  enabled: false
  interval: 50
  monsters: 50
  animals: 100
  
#Global! Which items SHOULD NOT be removed during removals? #ITEM-ID'S ONLY#
item-filter:
  enabled: false
  filter:
    - 264
  
#Meters your TPS, if it goes to low, run the commands you wrote below!
tps-meter:
  enabled: false
  interval: 15 
  tps-trigger: 14.0
  commands:
    - 'lagg killmobs'
    - 'limpar'
  
#This is /lagg killmobs, put what you DON'T want removed! 
kill-mobs:
   disable-build-wither: false 
   mob-filter:
        - Villager
        - Wolf
  
#This takes care of mob spawners
mobspawner:
  enabled: false
  max-spawn: 6
  
#No longer bugged! -- Dont use if you have CB++ or Spigot!
item-merger:
  enabled: false
  radius: 6
  
#Auto-removal options
auto-removal:
  broadcast-message: '&6&k==&0&l[&5Lixera&0]&6&k==&4Removidos +RemoveAmount Itens do Chao!'
  enable-scheduler: true
  enable-limit: true
  autoremoval-interval: 450
  
#The warning delay that runs AFTER auto-removal fires: This actually clears the items when it fires!
warning:
  autoremoval-warning: true
  autoremoval-warningdelay: 10
  broadcast-warning: true
  autoremoval-warningmessage: '&6&k==&0[&5Lixera&0]&6&k==&4Removendo Itens do Chao em 10 Segundos!'
  
#What should/not be removed during an auto-removal
remove:
  world-filter:
    - this_world
  broadcast-removal: true
  boat: true
  falling-block: true
  experienceOrb: true
  painting: true
  projectile: true
  item: true
  itemframe: false
  minecart: true
  primed-tnt: true
  arrow: true
  snowball: true
  fireball: true
  ender-signal: true
  mobs:
    - Creeper
    - Spider
    - Skeleton
    - Zombie
 
#What should/not be removed during /lagg clear 
command-remove:
  world-filter:
    - this_world
  broadcast-removal: false
  boat: true
  falling-block: true
  experienceOrb: true
  painting: true
  projectile: true
  item: true
  itemframe: false
  minecart: true
  primed-tnt: true
  arrow: true
  snowball: true
  fireball: true
  ender-signal: true
  mobs:
    - Creeper
    - Spider
    - Skeleton
    - Zombie
     
check:
  world-filter:
    - this_world
  boat: true
  falling-block: true
  experienceOrb: true
  painting: true
  projectile: true
  item: true
  itemframe: false
  minecart: true
  primed-tnt: true
  arrow: true
  snowball: true
  fireball: true
  ender-signal: true
  mobs:
    creature: true
    animals: true
    monster: true
     
limit:
  max: 2000
  check-interval: 60
  world-filter:
    - this_world
  broadcast-removal: true
  remove:
  boat: true
  falling-block: true
  experienceOrb: true
  painting: true
  projectile: true
  item: true
  itemframe: false
  minecart: true
  primed-tnt: true
  arrow: true
  snowball: true
  fireball: true
  ender-signal: true