# DeluxeChat version 1.11.1 config file
# Created by extended:clip
# list as many format sections you want under formats:
# each format section requires a default template that should be modified and
# also requires a unique number for the priority higher number = lower priority
# ex: guest-100, owner-1
#   YOU MUST KEEP A default TEMPLATE! It is used when players have no other template assigned!
#   
# example format template:
# formats: 
#   default:
#     priority: 2147483647
#     channel: ''
#     prefix: '&8[&7Guest&8] '
#     name_color: '&7'
#     name: '%player%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player% &bis a Guest'
#     prefix_tooltip:
#     - '&7%player% &bis a Guest'
#     name_tooltip:
#     - ''
#     suffix_tooltip:
#     - ''
#     channel_click_command: '
#     prefix_click_command: '/ranks
#     name_click_command: '/msg %player% 
#     suffix_click_command: '
#   Member:
#     priority: 100
#     channel: ''
#     prefix: '&8[&aMember&8] '
#     name_color: '&7'
#     name: '%player%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player% &bis a Member'
#     prefix_tooltip:
#     - '&7%player% &bis a Member'
#     name_tooltip:
#     - ''
#     suffix_tooltip:
#     - ''
#     channel_click_command: '
#     prefix_click_command: '/ranks
#     name_click_command: '/msg %player% 
#     suffix_click_command: '
check_updates: false
bungeecord:
  enabled: false
  servername: '&8[&cServer&8]'
  join_global: true
relation_placeholders_enabled: true
timestamp_format: MM/dd/yy
boolean:
  'true': '&atrue'
  'false': '&cfalse'
ops_use_group_format: false
hooks:
  javascript_placeholders: false
  minecraft_statistics: false
  acidisland: false
  askyblock: false
  autorank: false
  autosell: false
  banmanager: false
  battlelevels: false
  chatcolor: false
  chatreaction: false
  checknamehistory: false
  deluxetags: false
  essentials: false
  ezblocks: false
  ezprestige: false
  ezrankslite: false
  ezrankspro: true
  factions_mcore: false
  factions_uuid: false
  galistener: false
  gangsplus: false
  heroes: false
  islandworld: false
  jobs: false
  killrewards: false
  killstats: false
  marriagemaster: false
  mcinfected: false
  mcinfected-ranks: false
  mcmmo: false
  mvdw_placeholderapi: false
  nicky: false
  placeholderapi: false
  playerpoints: false
  plotme: false
  plotsquared: false
  prisongangs: false
  pvpstats: false
  quicksell: false
  royalcommands: false
  simpleclans: false
  simplecoinsapi: false
  simpleprefix: false
  simple_suffix: false
  skywarsreloaded: false
  sqlperms: false
  sqltokens: false
  survivalgames: false
  teams: false
  tokenenchant: false
  towny: false
  uskyblock: false
  ultimatevotes: false
  vanishnopacket: false
  vault_perms: true
  vault_eco: true
  voteparty: false
  werewolf: false
  wickedskywars: false
chat_filter:
  enabled: false
  list:
  - '.; '
  - fuck;fuck
private_message:
  enabled: true
  bungeecord: false
private_message_formats:
  to_sender:
    format: '&7Voce &e-> &7%player% &7:'
    tooltip:
    - '%player_server%'
    click_command: '/r '
    chat_color: '&f'
  to_recipient:
    format: '&7%player% &e-> &7Voce &7:'
    tooltip:
    - '%player_server%'
    click_command: '/r '
    chat_color: '&f'
  social_spy: '&8[&cspy&8] &f%player% &e-> &f%recipient%&7:'
formats:
  default:
    priority: 1000
    channel: ''
    prefix: '%vault_groupprefix%'
    name_color: '&f'
    name: '%player%'
    suffix: '&7: '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player%'
    - '&eMoney: %vaulteco_balance%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks
    prefix_click_command: /ranks
    name_click_command: '/msg %player% '
    suffix_click_command: ''
  vipsun:
    priority: 150
    channel: ''
    prefix: '%vault_groupprefix%&e[VipSun] '
    name_color: '&f'
    name: '%player%'
    suffix: '&7: '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player%'
    - '&eMoney: %vaulteco_balance%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks
    prefix_click_command: /ranks
    name_click_command: '/msg %player% '
    suffix_click_command: ''
  vipmoon:
    priority: 100
    channel: ''
    prefix: '%vault_groupprefix%&7[VipMoon] '
    name_color: '&f'
    name: '%player%'
    suffix: '&7: '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player%'
    - '&eMoney: %vaulteco_balance%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks
    prefix_click_command: /ranks
    name_click_command: '/msg %player% '
    suffix_click_command: ''
  mod:
    priority: 100
    channel: ''
    prefix: '%vault_groupprefix%&5&lMod '
    name_color: '&f'
    name: '%player%'
    suffix: '&7: '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player%'
    - '&eMoney: %vaulteco_balance%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks
    prefix_click_command: /ranks
    name_click_command: '/msg %player% '
    suffix_click_command: ''
  dono:
    priority: 100
    channel: ''
    prefix: '&4&l[Dono] '
    name_color: '&f'
    name: '%player%'
    suffix: '&7: '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player%'
    - '&eMoney: %vaulteco_balance%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks
    prefix_click_command: /ranks
    name_click_command: '/msg %player% '
    suffix_click_command: ''
