Tag: '&0&l[&3&lMito-PvP&0&l]&f-'
Mensagens:
  Novo: '&0&l[&3&lMito-PvP&0&l] &c@player e o(a) novo(a) MITO do PVP!'
  Atual: '&0&l[&3&lMito-PvP&0&l] &c@player e o(a) MITO do PVP!'
  Atual2: '&0&l[&3&lMito-PvP&0&l] &cSem mito do pvp no momento!'
  Logou: '&0&l[&3&lMito-PvP&0&l] &c@player logou no servidor!'
Mito: magois
