############################################################
# +-------- Designed and Developed by JackProehl --------+ #
# |--- Please consider donating to my PayPal account. ---| #
# +----------------- JohnProehl@me.com ------------------+ #
############################################################

# Add me on Skype (John.Proehl) if you have any issues.

# Please report all bugs and glitches on BukkitDev.

############################################################
# +------------------------------------------------------+ #
# |                     Miscellaneous                    | #
# +------------------------------------------------------+ #
############################################################

# Set "Enabled" to true to keep up with new improvements on the CombatLog project.
UpdateCheck:
  Enabled: true
  Message-Enabled: true
  
# Set "Message-Enabled" to true to add a custom MOTD message announcing the use of the CombatLog plugin.  
MOTD:
  Message-Enabled: false
  
# Set "Message-Enabled" to false to cancel the broadcasting of players who CombatLog.
Broadcast:
  Message-Enabled: true
  
############################################################
# +------------------------------------------------------+ #
# |                        Combat                        | #
# +------------------------------------------------------+ #
############################################################

# Duration is measured in increments of seconds. Ex: 300 = 300 seconds = 5 minutes.
# Set "PVE" to true to enable tagging upon Combat with hostile mobs.
# Set "PVP" to false to disable tagging upon Combat with other players.

# The Remove Modes features take away player's unfair advantages such as Flying or even Creative while in Combat.
# During Combat, their modes will be removed and all attempts to restore said modes during Combat will be denied.

# Set "OnKick" to true to remove players' tags if they are kicked during Combat. This cancels the punishments.

# Specify the potions to be removed upon entering Combat under "PotionTypes".
# A list of potion types can be found on the BukkitDev plugin page.

Tag:
  Message-Enabled: true
  Duration: 10
  PVP: true
  PVE: false
  Remove:
    Modes:
      Enabled: true
      Message-Enabled: true
      Creative: true
      Fly: true
    Tag:
      OnKick: true
    Potions:
      Enabled: true
      Message-Enabled: true
      PotionTypes:
      - INVISIBILITY
      
# Set "Message-Enabled" to false to cancel the info messages sent to the player.
Untag:
  Message-Enabled: true

# Limit the use of commands or completely block them while a player is in Combat.
# Set "Block-All" to true to block all commands. Otherwise, simply specify the commands you want blocked under "Commands."
DisabledCommands:
  Enabled: true
  Messages-Enabled: true
  Block-All: false
  Commands:
  - home
  - spawn
  - tpa
  - tpaccept
  - tpahere
  - warp
  - back

# To disable Combat tagging for ALL players in specific worlds, simply add the name of the World folder under "Worlds."
DisabledWorlds:
  Enabled: false
  Worlds:
  - world_nether
  - world_the_end
  
############################################################
# +------------------------------------------------------+ #
# |                      Punishments                     | #
# +------------------------------------------------------+ #
############################################################

# After a player logs out during Combat, the amount specified will be withdrawn from his bank account.
# The fine punishment does require the Vault plugin to work.
Fine:
  Enabled: true
  Message-Enabled: true
  Amount: 100.00
  
# After a player logs out during Combat, his belongings will be dropped accordingly.
Drop:
  Message-Enabled: true
  Inventory: true
  Armor: true
  Exp: false

# After a player logs out during Combat, he will be killed.
Kill:
  Enabled: true
  Message-Enabled: true
  
# After a player logs out during Combat, he will be temporarily banned.
# Duration is measured in increments of seconds. Ex: 300 = 300 seconds = 5 minutes.
# /combatlog unban allows one to manually unban a CombatLogger.
Ban:
  Enabled: true
  Duration: 10
