ConfigVersion: 1.9.6
UsePermissions: false
UseNicknames: false
Groups:
  membro:
    Colors:
    - ''
    Prefix: ''
  Youtuber:
    Colors:
    - '4'
    Prefix: ''
  Dono:
    Colors:
    - b
    Prefix: ''
  Admin:
    Colors:
    - '9'
    Prefix: ''
  Moderador:
    Colors:
    - 'a'
    Prefix: ''
  Construtor:
    Colors:
    - '5'
    Prefix: ''
  Vip:
    Colors:
    - '7'
    Prefix: ''
multi1:
- '2'
- o
multi2:
- e
- l
multi3:
- a
- o
multi4:
- a
- o
multi5:
- a
- o
multi6:
- a
- o
prefix1: new
prefix2: exp
prefix3: mod
prefix4: admin
prefix5: BOSS
prefix6: idk
