# PrivateKillMsg - versao(1.0) por heromax.
# Mensagens de morte privada.
# 
# Mensagem privada para quem MORREU!
MensagemVitima:
  ativar: true
  mensagem: '&3[WeepCraft] &d&l(vitima) foi morto por &c{assassino} e perdeu seu kdr treine mais moçu'
MensagemAssassino:
  ativar: true
  mensagem: '&3[WeepCraft] &b&l(assasino) humilhou &c{vitima} yea tu és pr0 =) '
SemPermissao: '&cVoce nao tem permissao para usar este comando!'
