# 
# Optional schematic specific configuration
lobby:
  world: SpawnServer
  spawn: 9.38 39.00 23.19 -177.30 12.75
  radius: 0
que:
  start-delay: -1
  min-start-player-count: 2
  sw-start-cost: 5
  max-wait-time: 180
  force-start-time: 21
score:
  per-kill: 3
  per-win: 7
  on-death: -1
  on-leave: -5
  groups:
    example:
      per-kill: 3
      per-win: 7
      on-death: -1
      on-leave: -5
schematics:
  schematic-name:
    min-players: 2
    timer: 11
  pinho:
    min-players: 2
    timer: 15
  Jungle:
    min-players: 2
    timer: 15
  Pinho:
    min-players: 2
    timer: 15
  Selva:
    min-players: 2
    timer: 15
  Gelo:
    min-players: 2
    timer: 15
  Bolo:
    min-players: 2
    timer: 15
  Savana:
    min-players: 2
    timer: 15
  Natal:
    min-players: 2
    timer: 15
statistics:
  update-interval: 600
  top: 30
data-storage: FILE
database:
  hostname: localhost
  port: 3306
  username: username
  password: password
  database: database
islands-per-row: 100
island-buffer: 5
island-building:
  enabled: false
  interval: 1
  blocks-per-tick: 20
build-cages: true
ignore-air: false
fill-empty-chests: true
fill-populated-chests: false
use-economy: true
enable-soundeffects: false
chat-handled-by-other-plugin: false
clear-inventory-on-join: false
save-inventory: true
whitelisted-commands:
- g
- global
disable-kits: false
Game:
  spawn-kill-timer: 20
