#########################################
########### GUIBox config file ##########
#########################################

#InventoryName
JukeboxMenuName: "&cSelect the song!"

#Lores:
WardLore: "&7Click to play Ward"
11Lore: "&7Click to play 11"
WaitLore: "&7Click to play Wait"
BlocksLore: "&7Click to play Blocks" 
ChirpLore: "&7Click to play Chirp" 
CatLore: "&7Click to play Cat" 
FarLore: "&7Click to play Far" 
MallLore: "&7Click to play Mall" 
MellohiLore: "&7Click to play Mellohi" 
StalLore: "&7Click to play Stal" 
StradLore: "&7Click to play Strad"
13Lore: "&7Click to play 13"


