# EnderPearl Cooldown
# Version 2
# Made by JMAK with luv <3
# DO NOT REMOVE THE '' AT THE BEGINNING AND ENDS OF THE LINES!!! (Will cause issues if you do!)

cooldownmsg: '&cYou are not aloud to throw an enderpearl for &c&l%time% &cseconds!'
cooldownendedmsg: '&a&lYou can now throw enderpearls!'
cooldown: 15

use-scoreboard: true
sb-title: '&d&lEPCooldown &cv6.3'
scoreboardline: '&6&lTime Left:'