name: KomboPvP
main: me.rafael.vinagre.KomboPvP.Main
version: Foda
author: [zEnderX5_]
#NAO MODIFICA O AUTOR POR FAVOR, NAO FOI VOCE QUE CRIOU O PLUGIN
website: https://www.youtube.com/channel/UCb1kjbiQj2B4KnRQpgeUwmQ
description: O Melhor plugin de KITPVP da internet

commands:
   
   chat:
   
   sobrevivente:
   gm:
   kits:
   kits2:
   cc:
   rank:
   rresponder:
   setar:
   setspawn:
   spawn:
   setwarp:
   warp:
   skit:
   sortear:
   s:
   testclick:
   tpc:
   tpall:
   warps:
   eventos:
   setfeast:
   setfeast2:
   setfeast3:
   setfeast4:
   setfeast5:
   spawn-feast:
   teleporter:
   alladin:
   anchor:
   archer:
   backpacker:
   barbarian:
   boxer:
   camel:
   ciclefire:
   confuser:
   critical:
   cyclope:
   darkgod:
   drain:
   ebola:
   fireman:
   fisherman:
   forcefield:
   fujao:
   gladiator:
   golen:
   grappler:
   hulk:
   indio:
   infernor:
   kangaroo:
   pvp:
   launcher:
   monk:
   netherman:
   ninja:
   poseidon:
   reaper:
   robinhood:
   ryu:
   snail:
   stomper:
   switcher:
   thor:
   thresh:
   timelord:
   turtle:
   velotrol:
   viking:
   viper:
   vitality:
   gaara:
   wither:
   invsee:
   fly:
   togglepvp:
   tp:
   tell:
   report:
   crash:
   stop:
   darxp:
   coins:
   lojadekits:
   loja:
   lojadoservidor:
   lojadeoutros:
   admin:
   autosoup:
   head:
   jellyfish:
   ping:
   bc:
   pesadelo:
   achilles:
   chestplate:
   tocha:
   resetfake:
   regras:
   frosty:
   efeitos:
   extra:
   efeito1:
   efeito2:
   efeito3:
   efeito4:
   efeito5:
   efeito6:
   efeito7:
   efeito8:
   removerefeito:
   tag:
   aplicar:
   removexp:
   naruto:
   info2:
   owner:
   jumper:
   grandpa:
   trocador:
   dj:
   flash:
   bloodgun:
  
   kills:
   youtuber:
   naruto:
   setarena:
   darkit:
   kits3:
   burstmaster:
   deshfire:
   nofall:
   sonic:
   subzero:
   quickdropper:
   avatar:
   caixas:
   doublejump:
   fake:
   status:
   gun:
   ver:
   help:
   build:
   
   
   
   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
  
   
   
   
   