recipes:
  LEATHER_HELMET: {}
  LEATHER_CHESTPLATE: {}
  LEATHER_LEGGINGS: {}
  LEATHER_BOOTS: {}
  IRON_HELMET: {}
  IRON_CHESTPLATE: {}
  IRON_LEGGINGS: {}
  IRON_BOOTS: {}
  DIAMOND_HELMET: {}
  DIAMOND_CHESTPLATE: {}
  DIAMOND_LEGGINGS: {}
  DIAMOND_BOOTS: {}
  GOLD_HELMET: {}
  GOLD_CHESTPLATE: {}
  GOLD_LEGGINGS: {}
  GOLD_BOOTS: {}
  CHAINMAIL_HELMET: {}
  CHAINMAIL_CHESTPLATE: {}
  CHAINMAIL_LEGGINGS: {}
  CHAINMAIL_BOOTS: {}
  GOLD_HOE: {}
  GOLD_SPADE: {}
  GOLD_PICKAXE: {}
  GOLD_AXE: {}
  WOOD_HOE: {}
  WOOD_SPADE: {}
  WOOD_PICKAXE: {}
  WOOD_AXE: {}
  STONE_HOE: {}
  STONE_SPADE: {}
  STONE_PICKAXE: {}
  STONE_AXE: {}
  IRON_HOE: {}
  IRON_SPADE: {}
  IRON_PICKAXE: {}
  IRON_AXE: {}
  DIAMOND_HOE: {}
  DIAMOND_SPADE: {}
  DIAMOND_PICKAXE: {}
  DIAMOND_AXE: {}
  FLINT_AND_STEEL: {}
  FISHING_ROD: {}
  SHEARS: {}
  BOW: {}
  WOOD_SWORD: {}
  GOLD_SWORD: {}
  STONE_SWORD: {}
  IRON_SWORD: {}
  DIAMOND_SWORD: {}
config:
  repairOfEnchantedItems:
    allow: false
    lose-enchantment: false
  usePermissions: false
  automaticRepair:
    allow: true
    no-warnings: false
    no-notifications: false
  anvilUse:
    allow: true
    anvilBlockType: IRON_BLOCK
  econCost:
    use: true
    adjust-for-damage: false
  xpCost:
    use: true
    adjust-for-damage: false
  itemCost:
    use: true
    adjust-for-damage: false
