AutoStart:
  Dia: sabado
  Hora: 1700
ClanTag: '[%tag%&r]&e '
Format:
  Ativar: true
  default: '%clan%&e'
  ops: '&c'
Premios:
  Mito:
    Ativar: true
    Cmd: pex user @player prefix &8&l[&6&lGladiador&8&l]-
  Tag: '&8[&6Gladiador&8] '
  Dinheiro: 50000
Timers:
  Preparar:
    Avisos: 20
    TempoEntre: 30
  Iniciando:
    Avisos: 10
    TempoEntre: 30
  Finalizando: 30
Arena:
  Entrada: world;0;0;0;0;0
  Saida: world;0;0;0;0;0
  Camarote: world;0;0;0;0;0
Update: 1
Vencedores: []
Bans:
  nicks:
    Por: magois
    Data: 24/04/2015
