# Arquivo de Linguagem (Modificavel)
language-file: lang-br.yml

# Lista de TODOS os items que podem ter o lore modificado. (Voce Pode Adicionar Novos Items se Quiser)
crafted-items:
- BOW
- FLINT_AND_STEEL
- FISHING_ROD
- COMPASS
- WATCH
- SHEARS
- LEASH
- WOOD_SWORD
- STONE_SWORD
- IRON_SWORD
- GOLD_SWORD
- DIAMOND_SWORD
- WOOD_SPADE
- STONE_SPADE
- IRON_SPADE
- GOLD_SPADE
- DIAMOND_SPADE
- WOOD_AXE
- STONE_AXE
- IRON_AXE
- GOLD_AXE
- DIAMOND_AXE
- WOOD_PICKAXE
- STONE_PICKAXE
- IRON_PICKAXE
- GOLD_PICKAXE
- DIAMOND_PICKAXE
- WOOD_HOE
- STONE_HOE
- IRON_HOE
- GOLD_HOE
- DIAMOND_HOE
- LEATHER_HELMET
- IRON_HELMET
- CHAINMAIL_HELMET
- GOLD_HELMET
- DIAMOND_HELMET
- LEATHER_CHESTPLATE
- IRON_CHESTPLATE
- CHAINMAIL_CHESTPLATE
- GOLD_CHESTPLATE
- DIAMOND_CHESTPLATE
- LEATHER_LEGGINGS
- IRON_LEGGINGS
- CHAINMAIL_LEGGINGS
- GOLD_LEGGINGS
- DIAMOND_LEGGINGS
- LEATHER_BOOTS
- IRON_BOOTS
- CHAINMAIL_BOOTS
- GOLD_BOOTS
- DIAMOND_BOOTS