#Aqui voce irá escolher qual som irá querer quando digitar um comando.

SomComandos: "NOTE_PLING"

#Sons disponiveis para colocar:
#NOTE_BASS_GUITAR
#NOTE_BASS
#NOTE_BASS_DRUM
#NOTE_BASS_GUITAR
#NOTE_PIANO
#NOTE_PLING
#NOTE_STICKS
