# This is the default config.yml of SimpleBroadcast.
# Plugin made by KingDome24.
# If you need help visit https://www.SimpleBroadcast.net
# Please be sure that all your messages are inside of single quotes!
# The update checking requires an Internet connection.

enabled: true

delay: 60 # time in seconds

prefix:
  enabled: true
  prefix: '&d[Broadcast]&7'
  
suffix:
  enabled: false
  suffix: '&d[v1.9.2]'

checkforupdates: true

randomizemessages: false

requiresonlineplayers: false

sendmessagestoconsole: false

messages:
- 'Thank you for using SimpleBroadcast!'
- 'Plugin by &oKingDome24.'
- 'If you have any questions please visit the website or BukkitDev.'
- 'JSON:{text:"You want a text with awesome effects? Use JSON messages!","color":"yellow",hoverEvent:{action:show_text,value:[{text:"You will like them!",color:blue}]}}'