# DiscoFloor v1.0 - Configuration
#
# The delay between each recalculation of the blocks in the disco floors
# in ticks; 1 second = 20 ticks
# Smaller amounts can cause lag
ColorSwitchTime: 5
# The id of the blocks used in the disco floors
Blocks:
- 95
- '95:1'
- '95:2'
- '95:3'
- '95:3'
- '95:4'
- '95:5'
- '95:6'