name: FireLibs
version: 1.0
main: neero.demon.Main
commands:
  check:
  kit:
  kits:
  escalador:
  pchat:
  cc:
  grapler:
  invis:
  vis:
  achilles:
  skit:
  anchor:
  archer:
  assassin:
  barbarian:
  berserker:
  boxer:
  warn:
  demoman:
  antistomper2:
  ajudante:
  sniper:
  ranks:
  extra:
  villagerparkour:
  anchor2:
  clicktest:
  selector:
  zeca:
  lojaitens:
  loja:
  ajuda:
  aplicar:
  admin:
  togglepvp:
  kick:
  escapist:
  fisherman:
  ban:
  neo:
  fly:
  gambler:
  hulk:
  ebola:
  kit2:
  stomper2:
  ajnin2:
  setarena:
  kangaroo:
  launcher:
  pesadelo:
  phantom:
  pikachu:
  poseidon:
  reaper:
  salvager:
  skyrunner:
  snail:
  sonic:
  soulstealer:
  souper:
  specialist:
  stomper:
  tank:
  thor:
  timelord:
  tocha:
  turtle:
  urgal:
  vampire:
  viking:
  vulture:
  viper:
  pvp:
  caio:
  ph:
  brackets:
  pl:
  admin:
  fly:
  crash:
  gm:
  head:
  inv:
  report:
  s:
  tp:
  fake:
  suicide:
  sumo:
  warp:
  warps:
  serverinfo:
  gladiator:
  tag:
  youtuber:
  setrdm:
  setspawn:
  setfps:
  setchallenge:
  setmdr:
  burstmaster:
  zikavirus:
  booster:
  recraft:
  mdr:
  rdm:
  spawn:
  fps:
  challenge:
  setsouper:
  tell:
  r:
  challenger:
  broadcast:
  bc:
  ping: