usingConfig: true
config-version: 3
using-bungeecord: false
legacy-client-support: false
updater:
  check-automatically: true
tabmenu:
  enabled: false
  header: '\n \n &6&lSmarthMC \n             &a \n '
  footer: '\n \n &aTwitter : &f@ServidoresSmart \n \n             &aSite :&a SEU SERVER '
welcome_message:
  enabled: true
  title: '&6&lFactions'
  subtitle: '&aSyan-network'
  fadeIn: 60
  stay: 40
  fadeOut: 60
  first-join:
    title: '&6&lFactions'
    subtitle: '&aSEU SERVER'
actionbar-welcome:
  enabled: false
  message: ''
  first-join:
    message: ''
number-format:
  enabled: true
  format: '#,###.##'
date-format:
  format: EEE, dd MMM yyyy HH:mm:ss z
disabled-variables:
- my-disabled-variable
- also-called-placeholders
