# This config controls what plugins work on certain worlds.
# Example
# limit:
#   WorldEdit:
#     - world
#     - world_nether
#   Essentials: []
# This will make it so worldedit will only work in world & world_nether, meaning in the end it is not usable.
# When there is no worlds in the list it will allow it for any worlds, in this example allowing all worlds.
# Whenever a plugin is added, this config will automatically add it!
# exempt-login-events is for excluding login events when true, this means if a plugin uses PlayerLogin it will allow it for any world. We advise this to be enabled!
# blocked-msg is the string displayed to a client when a command is blocked
# check-for-updates is the controller for if updates should be alerted to the users with the permissions/op.
exempt-login-events: true
check-for-updates: true
blocked-msg: '&cComando Invalido. Use: &a/ajuda&c.'
limit:
  frostRenamer: []
  Troll: []
  ColoredSigns: []
  CraftX1: []
  GroupManager: []
  PluginManager: []
  AlphaChest: []
  ItemBans: []
  SaveIt: []
  AntiRelog: []
  MaxBans: []
  LsMobsVsPlayers: []
  HeadDrops: []
  kYouTuber: []
  DrugsXL: []
  FunnyEffect: []
  Color4Signs: []
  ZavAutoMessager: []
  FlyingCarpet: []
  WorldEdit: []
  VipShop: []
  TimTheEnchanter: []
  HeadHunter: []
  MoreSounds: []
  Essentials: []
  LuckyBlocks: []
  ClearLag: []
  CWChuva_By_Matgsan: []
  MagicCarpet: []
  EndlessEnchant: []
  LikeSigns: []
  Killer: []
  ProtocolLib: []
  NoCheatPlus: []
  KitAdder: []
  Loteria: []
  CustomServerMessages: []
  Shopkeepers: []
  TGReport: []
  Predador: []
  CidadeMortalChat: []
  EssentialsChat: []
  iConomy: []
  Microblocks: []
  PermissionsEx: []
  MineReward:
  - SPAWN
  mcMMO: []
  Vault: []
  MoneyMobs: []
  MinigamesLib: []
  Rankup:
  - SPAWN
  VipZero: []
  TagAPI: []
  WorldGuard: []
  EasyTrading: []
  Legendchat: []
  ChestCommands: []
  EssentialsGeoIP: []
  TriviaMaster: []
  Skins: []
  Magnata: []
  EssentialsSpawn: []
  MyCommand: []
  AutoRepair: []
  CombatLog: []
  PlotMe: []
  Jobs: []
  SilkSpawners: []
  Multiverse-Core: []
  SimpleClans: []
  Citizens: []
  DiscoFloor: []
  AncientGates: []
  BuyRegion: []
  SimplesTags: []
  MineResetLite: []
  GiantTrees: []
  ChestShop: []
  HeroClanTags: []
  ShowCaseStandalone: []
  MitoDoPvP: []
  HolographicDisplays: []
  ChestRegen: []
  MyPet: []
  CommandSigns: []
  AuthMe: []
  UltimateParticles: []
  SexyMotd: []
  RPG_Items: []
  GriefLog: []
  MotdManager: []
  PVP_Flight: []
  AntiCreeper3: []
  LWC:
  - plotworld
  - world
  - world_nether
  - world_the_end
  EssentialsProtect: []
  EssentialsAntiBuild: []
  Info_Board: []
  SuperPotions: []
  TempleRunBR: []
  GriefPrevention: []
  JoinCommands: []
  FireworkBuilder: []
