broadcast:
  pre: '&eVou fazer Um Save Do Mapa &6&lPODE LAGAR'
  post: '&eOcorreu Tudo Bem Ja Fiz O Save &BBOM JOGO'
broadcastbackup:
  pre: '&9AutoBackuping'
  post: '&9AutoBackup Complete'
broadcastpurge:
  pre: '&9AutoPurging'
  post: '&9AutoPurge Complete'
insufficentpermissions: '&cYou do not have access to that command.'
autorestart:
  restarting: '&e&lO Servidor Vai Reiniciar EM Instantes'
  countdown: '&e&lServidor Vai Reiniciar Em {SECONDS} Segundos'
worldregen:
  kickmessage: '&9Servidor Estar Criando o Mapa, Voltamos Em Instantes'
