# TriviaMaster Configuration
questions: 
  - "Quem e o Verdadeiro Dono Do Minecraft?"
  - "Qual e o Principal Motivo Dos Erros?"
  - "Quanto e 25+32-68?"

# Answers must match up with the order of the questions
answers:
  - "notch"
  - "provas"
  - "-11"

# Number of questions to ask in an event; 0 to ask all
numOfQuestions: 0

# Randomize questions?
randomize: true

# Requires vault to use
moneyReward: 2500.0

# Item - Amount - Data Value
itemRewards:
  - 4 5

# Time in seconds for a question to last before skipping it
duration: 600

# Time in seconds to wait between questions
timeBetween: 5

##################

# Language Options
# Default color codes supported
startMessage: "&aEvento Quiz &6Iniciou ! &aBoa Sorte..."
timeUp: "&6Vamos Para O Proximo Nivel? "
endMessage: "&6O &aEvento Quiz &6Acabou!"
oneWinner: "&6O Vencedor Do &aEvento Quiz &6e &a&l[winner] &6Com &a[points] &6Pontos!"
tiedWinners: "&6The winners of the Trivia Event are (tied for &4[points] &6points):"
noWinners: "&6Ninguem Ganhou No &aEvento Quiz&6 !"

# You cannot modify point values at this time
answered: "&6O Jogador &a&l[player] &6Acertou a Resposta!"
