#Mensagens
Mensagens:
  errado: '&e[Punir] &cUse /punir <usuario>'
  invalido: '&e[Punir] &c%nome% não é um jogador.'
  inserirprova: '&e[Punir] &4Insira sua prova:'
  sempermissao: '&4Você não tem permissão para usar esse comando.'

Punicoes:
  #Nome da punicao
  Flood:
    #Permissao para punir
    permissao: gcpunir.flood
    #Caso vocÊ queira que o staff insira uma prova deixe como true, caso não queira deixe como false
    prova: false
    #pode criar quantos comandos quiser para cada ocorrencia por exemplo o comando 1 vai ser aplicado quando for a primeira vez que o player for banido por floor
    comandos:
      #use %suspeito% para o nome de quem vai banir e %prova% para a prova.
      '1': tempmute %suspeito% 15m Flood 1xAviso (%prova%)
      '2': tempmute %suspeito% 1h Flood 2xAviso (%prova%)
      '3': tempban %suspeito% 3h Flood 3xAviso (%prova%)
  X-Ray:
    permissao: gcpunir.xray
    prova: false
    comandos:
      '1': banip %suspeito% Uso de X-Ray
      
#NAO MEXER A PARTIR DAQUI!!
Dados:

