# default config.yml for CustomEnderChest
# config version 1.4.2

#Database settings
database:
    #Type of database, Options: FlatFile or MySQL
    typeOfDatabase: FlatFile
    #MySQL database type connection details.
    mysql:
        host: 127.0.0.1
        port: 3306
        databaseName: 'mydatabase'
        tableName: 'cec_enderchests'
        user: 'admin'
        password: 'cheesecake'
        #This task will scan the mysql database for inactive players and remove them.
        #The scanning takes place after server starts with a 2min delay. Runs on a async thread so server performance will not be affected.
        removeOldUsers:
            #Enable or disable mysql database maintenance. | (true or false)
            enabled: false
            #Inactivity in days. Default 60 days.
            inactive: 60

#Customize Ender Chest Title
enderChestTitle:
    #EnderChest folder name. Supports color and format codes.
    #Minecraft Color and Format Codes: http://minecraft.gamepedia.com/Formatting_codes
    #WARNING! Max size is 32 characters including color, format codes.
    enderChestName: '&8Enderchest &8- &8@%player'
    
    #The place holder  %player  will be replaced by player's name.
    
    #The  %level  place holder replace text below. So you can customize each enderchest title by enderchest size.
    
    #For 9 slots enderchest.
    level0: '&aLevel 0'
    #For 18 slots enderchest.
    level1: '&aLevel 1'
    #For 27 slots enderchest.
    level2: '&aLevel 2'
    #For 36 slots enderchest.
    level3: '&5Level 3'
    #For 45 slots enderchest.
    level4: '&5Level 4'
    #For 54 slots enderchest.
    level5: '&5Level 5'

#Chat messages. Supports color and format codes. 
chatMessages:
    #Chat messages prefix.
    #To disable the prefix set it to '' ; Example: prefix: ''
    prefix: '&a'
    
    #Disable any chat message by setting it to '' | Example: noPermission: ''
    #Chat messages.
    noPermission: '&cVoce precisa do grupo Paladino ou superior para executar este comando.'
    openCmdUsage: '&aUse: &7/customec open John &aor &7/customec open f694517d-d6cf-32f1-972b-dfc677ceac45'
    noEnderchest: '&aPlayer does not have and Ender Chest yet!'
    openUuidFail: '&aPlayer does not have and Ender Chest or wrong UUID!'
    openNameOffline: '&aPlayer offline or wrong UUID! Use: &7/customec open <playerUUID>'
    deleteNameOffline: '&aPlayer offline or wrong UUID! Use: &7/customec delete <playerUUID>'
    deleteCmdUsage: '&aUsage example: &7/customec delete John &aor &7/customec delete f694517d-d6cf-32f1-972b-dfc677ceac45'
    delete: '&aPlayer enderchest data removed!'
    reloadFail: '&aCould not load config! Check logs!'
    reload: '&aConfiguration reloaded!'