desativado: '&aModo voar desativado !'
ativado: '&aModo voar ativado !'
sempermisao: "&cVocê não tem permissão."
bloqueado: "&4O modo voar não é permitido nesse mundo!"
comando: "/voar"
#Não use cor no comando...
mundosbloqueados:
- "world"
- "minerar"
- "fps"
- "eventos"