#--------
#Não mexa nessa config!
#Esta config tem coisas importantes.
#HG V1.0 BY: IGAOSTENDECOMPILER

FakesAleatorios:
- 'ySloowy_'
- 'JoaozinhU'
- '_PaatoPvP'
- 'zSt3nn'
- 'uScrolling_'
- 'getStep_'
- 'yStupidPVP_'
- 'Grakow_'
- 'SwipWG'
- 'noLyte'
- 'SpolerHG'
- 'yN00B_'

chanceminifeast: 65


minifeast:
- 46,2,6,false
- 261,1,1,false
- 262,3,9,false
- 265,3,7,true
- 266,4,9,true
- 272,1,1,false
- 327,1,1,false
- 326,1,1,false
- 351;3,3,15,false
- 364,2,9,false
- 373;16388,1,1,true
- 373;16426,1,1,false

FeastItems:
- 310,1,1,true
- 311,1,1,true
- 312,1,1,true
- 313,1,1,true
- 276,1,1,true
- 278,1,1,true
- 327,1,1,true
- 30,1,10,false
- 368,3,13,true
- 259,1,1,true
- 320,1,20,true
- 262,1,30,true
- 364,1,20,true
- 322,1,5,true
- 297,1,20,false
- 261,1,1,true
- 46,1,20,true
- 384,1,20,true
- 373;16484,1,1,true
- 373;16458,1,1,true

chancefeast: 30
