KickMsg: Someone with a higher rank joined you were randomly selected for kicking.
SorryMsg: No one was found with a lower rank. :(
Permissions: true
PEXRankSystem: false
defaultRank: 100
permissionBasedRanks: 10
Broadcast: '[Reservations]: %lowerrank% have been kicked because %higherrank% joined.'
preventKickFromAnotherLocationLogin: true
loginFromAnotherLocationMessage: You are already logged in from another location!
Ranks:
  HomerBond005: 1
VIPs:
- Admin
- HomerBond005
updateReminderEnabled: true
