Strength: 1.0
Up: 1.0
mobUse: false
Sound: 1
NoFallDamageTimeMob: 3
UnlimitedPlates: true
Plates:
  location:
  - 4-29--13-Hubria
  - 6-29--13-Hubria
  - 5-29--13-Hubria
  - -9-29-0-Hubria
  - -9-29-1-Hubria
  - -9-29-2-Hubria
  - 5-29-15-Hubria
  - 6-29-15-Hubria
  - 4-29-15-Hubria
  - 19-29-2-Hubria
  - 19-29-1-Hubria
  - 19-29-0-Hubria
  - 828-4-38-Hubria
  - 828-4-39-Hubria
  - 828-4-37-Hubria
  - 843-4-38-Hubria
  - 843-4-37-Hubria
  - 843-4-39-Hubria
  - 858-4-37-Hubria
  - 858-4-39-Hubria
  - 858-4-38-Hubria
  - 873-4-37-Hubria
  - 873-4-38-Hubria
  - 873-4-39-Hubria
  - 16-38-12-Hubria
  - 16-38--10-Hubria
  - -6-38--10-Hubria
  - -6-38-12-Hubria
  - -29-29--2-Hubria
