# Default config for ZavAutoMessager.
# Visit http://dev.bukkit.org/server-mods/zavautomessager/ for more help
# Plugin created by the ZavCoding Team
# Authors: javoris767 and zachoooo.
# Make sure all your messages are inside of single quotes. (This makes sure that color and special characters work properly)
# If you want to make your own line breaks MAKE SURE WORDWRAP IS FALSE!!! Custom line breaks are only supported when wordwrap is off.
# Update checking requires an internet connection.
# Set update checking to false if you have no internet connection or you have a very strict firewall.

enabled: true

wordwrap: true

delay: 60 # In Seconds

permissionsenabled: false # If true, only people with permission can view the message.

chatformat: '[&6NextFactions&f]: %msg'

messageinrandomorder: false # Should the messages be displayed in a random order

updatechecking: true

messagesinconsole: true

requireplayersonline: true

dontrepeatrandommessages: true

messages:
    default:
    - '&6&l Ajude o Servidor Ficar Online Comprando Vip ou Cash Digite /site '
    - '&6&l Mate Jogadores e Venda a Cabeca dele para o Silver Digite /warp almas'
    - '&6&l Use seu xp digite /encantar!'