#####################################################################################################
#                                       												            #
#           					 PLUGIN EM FAZE DE TESTE                							#
#                                                   												#
# 					CONFIG.YML SERA ADICIONADA NAS PROXIMAS ATUALIZAÇOES							#
#                                                   												#
#####################################################################################################
#																									#
# - BUKKIT: https://dev.bukkit.org/bukkit-plugins/stackmobs/                                        #
#                                         															#
# - PARA SER NOTIFICADO NOVOS UPDATES PREENCHA O FORMULARIO: https://goo.gl/forms/kJ0RXyMQvUoolD183 #
#																									#
#####################################################################################################

#Cores: azul, vermelho, verdeclaro, verde, laranja, preto, rosa, roxo, branco
CorDoNome: 'verdeclaro'

Tags:
  Servidor: '&0[&1LieStarSkies&0]&f '

MensagemAoMatarMob:
  Ativo: 'true'
  Mensagem: '&aParabens, voce acabou de matar varios mobs de uma vez!'