
# Tempo de cada habilidade com Double XP; (vale lembrar que o DELAY é em segundos)
Tempos:

  Espada: 300
  Machado: 300
  Acrobacia: 300
  Mineracao: 300
  Alquimia: 300
  Herbalismo: 300
  Escavacao: 300
  Arqueiro: 300
  Reparacao: 300
  
# Valor para comprar o DOUBLE XP;
Valores:

  Espada: 1000000
  Machado: 1000000
  Acrobacia: 1000000
  Mineracao: 1000000
  Alquimia: 1000000
  Herbalismo: 1000000
  Escavacao: 1000000
  Arqueiro: 1000000
  Reparacao: 1000000
  
# Aqui vai ser quando o jogador comprar a habiliade, vai multiplicar por quanto?
Multiplicador:

  Espada: 2
  Machado: 2
  Acrobacia: 2
  Mineracao: 2
  Alquimia: 2
  Herbalismo: 2
  Escavacao: 2
  Arqueiro: 2
  Reparacao: 2
  
# Mensagens Pessoais Configuráveis;
Mensagens:

  BoosterAtivo: "&cOps, o boster @booster ja esta ativo!" # Quando o jogador tentar comprar um booster já ativo;
  BoosterAcabou: "&cOps, o boster @booster acabou!" # Quando o booster do jogador terminar;
  BoosterAtivou: "&aVoce ativou o boster @booster por 300 segundos!" # Quando ele ativar o booster;
  SemPermissao: "&cVoce nao tem permissao para isso!" # Quando ele tentar dar reload no plugin;
  SaldoInsuficiente: "&cSeu saldo e insuficiente!" # Quando o saldo dele for insuficiente;

  # Mensagens Globais Configuráveis;
Globais:
  
  BoosterAtivouGeral: "&a&lvBoosterMcMMO &8» &a@jogador &7ativou booster de &a@booster &7por @tempo &7segundos!" # Mensagem ativou para todos
  BoosterAtivouGeralTitle: "&a@jogador" # Mensagem ativou para todos
  BoosterAtivouGeralSubtitle: "&7ativou um booster de @booster por @tempo segundos" # Mensagem ativou para todos
  
# Caso esteja true, a mensagem GLOBAL será em Title
# Caso esteja false, a mensagem GLOBAL será em Chat
  
Title:
  Status: true