world:
  world:
    enabled: true
    start:
      time: 12500
      msg:
        text: '&cIt''s night and PvP is turned on'
        broadcast: true
      cmd: ''
      changeWorldMsg:
        enabled: true
        text: '&aHey, PvP is off!'
      sound:
        enabled: false
        name: ENDERDRAGON_GROWL
        volume: 10
        pitch: 2
    end:
      time: 500
      msg:
        text: '&aIt''s daytime and PvP is turned off'
        broadcast: true
      cmd: ''
      sound:
        enabled: false
        name: NOTE_PLING
        volume: 10
        pitch: 1
    forcePvP: false
    override: false
    antiFirePvP:
      enabled: false
      msg: '&cIt''s day time, you can''t place lava or fire'
      smart: false
      items:
      - FIRE
      - FLINT_AND_STEEL
      - LAVA
      - LAVA_BUCKET
      - FIREBALL
      - STATIONARY_LAVA
  world_the_end:
    enabled: false
    start:
      time: 12500
      msg:
        text: '&cIt''s night and PvP is turned on'
        broadcast: true
      cmd: ''
      changeWorldMsg:
        enabled: true
        text: '&aHey, PvP is off!'
      sound:
        enabled: false
        name: ENDERDRAGON_GROWL
        volume: 10
        pitch: 2
    end:
      time: 500
      msg:
        text: '&aIt''s daytime and PvP is turned off'
        broadcast: true
      cmd: ''
      sound:
        enabled: false
        name: NOTE_PLING
        volume: 10
        pitch: 1
    forcePvP: false
    override: false
    antiFirePvP:
      enabled: false
      msg: '&cIt''s day time, you can''t place lava or fire'
      smart: false
      items:
      - FIRE
      - FLINT_AND_STEEL
      - LAVA
      - LAVA_BUCKET
      - FIREBALL
      - STATIONARY_LAVA
  plotworld:
    enabled: true
    start:
      time: 12500
      msg:
        text: '&cIt''s night and PvP is turned on'
        broadcast: true
      cmd: ''
      changeWorldMsg:
        enabled: true
        text: '&aHey, PvP is off!'
      sound:
        enabled: false
        name: ENDERDRAGON_GROWL
        volume: 10
        pitch: 2
    end:
      time: 500
      msg:
        text: '&aIt''s daytime and PvP is turned off'
        broadcast: true
      cmd: ''
      sound:
        enabled: false
        name: NOTE_PLING
        volume: 10
        pitch: 1
    forcePvP: false
    override: false
    antiFirePvP:
      enabled: false
      msg: '&cIt''s day time, you can''t place lava or fire'
      smart: false
      items:
      - FIRE
      - FLINT_AND_STEEL
      - LAVA
      - LAVA_BUCKET
      - FIREBALL
      - STATIONARY_LAVA
  craft2:
    enabled: true
    start:
      time: 12500
      msg:
        text: '&cIt''s night and PvP is turned on'
        broadcast: true
      cmd: ''
      changeWorldMsg:
        enabled: true
        text: '&aHey, PvP is off!'
      sound:
        enabled: false
        name: ENDERDRAGON_GROWL
        volume: 10
        pitch: 2
    end:
      time: 500
      msg:
        text: '&aIt''s daytime and PvP is turned off'
        broadcast: true
      cmd: ''
      sound:
        enabled: false
        name: NOTE_PLING
        volume: 10
        pitch: 1
    forcePvP: false
    override: false
    antiFirePvP:
      enabled: false
      msg: '&cIt''s day time, you can''t place lava or fire'
      smart: false
      items:
      - FIRE
      - FLINT_AND_STEEL
      - LAVA
      - LAVA_BUCKET
      - FIREBALL
      - STATIONARY_LAVA
  plotworld2:
    enabled: false
    start:
      time: 12500
      msg:
        text: '&cIt''s night and PvP is turned on'
        broadcast: true
      cmd: ''
      changeWorldMsg:
        enabled: true
        text: '&aHey, PvP is off!'
      sound:
        enabled: false
        name: ENDERDRAGON_GROWL
        volume: 10
        pitch: 2
    end:
      time: 500
      msg:
        text: '&aIt''s daytime and PvP is turned off'
        broadcast: true
      cmd: ''
      sound:
        enabled: false
        name: NOTE_PLING
        volume: 10
        pitch: 1
    forcePvP: false
    override: false
    antiFirePvP:
      enabled: false
      msg: '&cIt''s day time, you can''t place lava or fire'
      smart: false
      items:
      - FIRE
      - FLINT_AND_STEEL
      - LAVA
      - LAVA_BUCKET
      - FIREBALL
      - STATIONARY_LAVA
