MySQL:
  Ativar: false
  User: root
  Password: '123'
  Host: localhost
  Database: bMIITO
Ativacoes:
  Mensagem-Join: true
  Mensagem-Quit: true
Quantidade-De-Raios: 5
Total-De-Tops: 3
Comandos-A-Serem-Executados:
- pex user <oldmito> remove bukkit.command.say
- pex user <newmito> add bukkit.command.say
- say teste
Mensagens:
  Cabecalho: '&5[&cTOP-MITOS&5]'
  PlayerTop: '&5[&c<posicao>&5]&c<player>&5: Pegou a &5&l[MITO] &c<quantidade> &5vezes.'
  MinhaQuantidade: '&5Voce pegou a &5&l[MITO] &c<quantidade> &5vezes.'
  TargetQuantidade: '&c<player> &5pegou a &5&l[MITO] &c<quantidade> &5vezes.'
  NewMito: '&5&l[MITO] O]&5Novo mito do PvP -> <newmito>'
  MostrarMito: '&5&l[MIT &c&l<mito>'
  SemMito: '&5&l[MITO] Mito indefinido.'
  MitoDead: '&5&l[MITO] &5O MITO &c<mito> &5faliceu. Novo Mito: &c<newmito>&5.'
  MitoJoin: '&5&l[MITO] &5O MITO &c<mito> &5logou no servidor.'
  MitoQuit: '&5&l[MITO] &5O MITO &c<mito> &5deslogou do servidor.'
  ArgsErros: '&5&l[MITO] &cUse: /setmito <jogador>.'
  SemPermissao: '&cSem Permissao.'
MitoFormato: '&c&l[MITO]'
MitoAtual: J4ilson_dlc
MitoAntigo: J4ilson_dlc
