nopermission: '&cVoce nao tem permission'
teleporttolobby: '&6Voce foi teleportado para o &aLobby'
availablearenas: '&6Arenas: &a '
arenawolrdna: '&6Mundo desta arena nao esta carregado'
arenadisabled: '&6Arena desabilitada'
arenarunning: '&6Arena esta em funcionamento'
arenaregenerating: '&6Arena esta sendo regenerada'
arenavehicle: '&6Voce no pode entrar na arena quando estiver num cavalo ou porco'
arenadisabling: '&6Arena esta sendo desabilitada'
playerscountinarena: '&6Numero de jogadores nesta arena: &a{COUNT}'
limitreached: '&6Limite de jogadores alcansado.'
playerjoinedtoplayer: '&6Voce entrou no jogo'
playerjoinedtoothers: '&6O jogador &a{PLAYER}&6 entrou na arena'
playerlefttoplayer: '&6Voce saiu da arena'
playerlefttoothers: '&6O jogador &a{PLAYER}&6 saiu da arena'
playervotedforstart: '&6Voce votou para comecar o jogo'
playeralreadyvotedforstart: '&6Voce ja votou'
arenastarted: '&6Arena comecou. Tempo para acabar &a{TIMELIMIT} &6segundos'
arenacountdown: '&6Arena comecara em &a{COUNTDOWN} &6segundos'
arenatimeout: '&6O tempo acabou'
playerwontoplayer: '&6Voce venceu o jogo'
playerlosttoplayer: '&6Voce perdeu o jogo'
playerlosttoothers: '&6O jogador &a{PLAYER} &6perdeu o jogo'
playerwonbroadcast: '&c[&4TNTRun&c] &6O jogador &a{PLAYER}&r venceu o jogo na arena &a{ARENA}'
playerrewardmessage: '&6Voce ganhou: &a{REWARD}'
