DelayInMinutes: 20
SaveAllWorlds: false
Worlds:
- world
- plotworld
EnableSaveMSG: true
SaveMSG: '&aSalvando o mundo'
SaveMSG2: '&aO Mundo foi salvado com sucesso!'
SavePlayersEverywhere: false
CheckForUpdates: true
DisableDefaultWorldSave: false
ExtraOptions:
  SaveOnLogin: false
  SaveOnLoginCount: 50
  SaveOnQuit: false
  SaveOnQuitCount: 50
  SaveOnBlockBreak: false
  SaveOnBlockPlace: false
  SaveOnBlockBreakcount: 500
  SaveOnBlockPlacecount: 500
  EnableSelfInventorySave: false
  EnableDebugMSGs: false
  CheckSavingStats: false
EnablePowerSave: false
BroadCastWorldErrorIg: false
BackUp:
  EnableBackup: true
  EnableBackupMSG: true
  EnableAutoBackup: false
  EnablePlayerKickWhileBackup: false
  KickMSG: Server is making a backup...
  IntervalOrDay: INTERVAL
  BackupHoursInterval: 2
  Date: 0
  DateDayDelay: 7
  EnableBackupPurge: false
  AutoPurge: false
  RemoveBackupXAfterDay: 4
  EnableMaxBackups: true
  MaxBackups: 10
  WarningMSG: '&aBackup Foi iniciado!'
  WarningMSG2: '&aBackup Finalizado!'
  DirectoryNotToBackup:
  - thisisntgoingtobebackuped
