# Spawner config file
# 
# Valid entities
valid_entities:
- Creeper
- Skeleton
- Spider
- Giant
- Zombie
- Slime
- Ghast
- PigZombie
- Enderman
- CaveSpider
- Silverfish
- Blaze
- LavaSlime
- EnderDragon
- WitherBoss
- Bat
- Witch
- Pig
- Sheep
- Cow
- Chicken
- Squid
- Wolf
- MushroomCow
- SnowMan
- Ozelot
- VillagerGolem
- EntityHorse
- Villager
- FireworksRocketEntity
- Guardian
- Endermite
- Rabbit
aliases:
  WitherBoss:
  - wither
  VillagerGolem:
  - irongolem
  - golem
  EntityHorse:
  - horse
  Ozelot:
  - ocelot
  - cat
protect_from_explosions: false
drop_from_explosions: true
remove_radius: 10
luck: 100
frequency:
  creeper: 100
  skeleton: 100
  spider: 100
  giant: 100
  zombie: 100
  slime: 100
  ghast: 100
  pigzombie: 100
  enderman: 100
  cavespider: 100
  silverfish: 100
  blaze: 100
  lavaslime: 100
  enderdragon: 100
  witherboss: 100
  bat: 100
  witch: 100
  pig: 100
  sheep: 100
  cow: 100
  chicken: 100
  squid: 100
  wolf: 100
  mushroomcow: 100
  snowman: 100
  ozelot: 100
  villagergolem: 100
  entityhorse: 100
  villager: 100
  fireworksrocketentity: 100
  guardian: 100
  endermite: 100
  rabbit: 100
drops:
  Creeper: 30
  Skeleton: 30
  Spider: 30
  Giant: 30
  Zombie: 30
  Slime: 30
  Ghast: 30
  PigZombie: 30
  Enderman: 30
  CaveSpider: 30
  Silverfish: 30
  Blaze: 30
  LavaSlime: 30
  EnderDragon: 30
  WitherBoss: 30
  Bat: 30
  Witch: 30
  Pig: 30
  Sheep: 30
  Cow: 30
  Chicken: 30
  Squid: 30
  Wolf: 30
  MushroomCow: 30
  SnowMan: 30
  Ozelot: 30
  VillagerGolem: 30
  EntityHorse: 30
  Villager: 30
  FireworksRocketEntity: 30
  Guardian: 30
  Endermite: 30
  Rabbit: 30
