name: HungerGames
author: SkillNetwork
version: 2.7
main: Net.Hunger.Main
depend: [ProtocolLib]
commands:
  iniciar:
  kits:
  kit:
  help:
  admin:
  chat:
  toggle:
  checar:
  ip:
  gm:
  s:
  help:
  fly:
  info:
  feast:
  pvp:
  togglekit:
  spawn:
  sc:
  forcefeast:
  aplicar:
  who:
  tag:
  miniarena:
  tp:
  spec:
  tpall:
  invencibilidade:
  game:
  pregame:
  invis:
  tell:
  ir:
  f:
  skit:
  inv:
  arena:
  vis:
  watch: