#Configuracao de Home.
Home:
  #Permissao para poder setar, deletar ou ir a uma home.
  Permissao: "factionmania.home.usar"
  Sem_Permissao: "&cVoce precisa do grupo Vip ou superior para executar este comando"
  Erro: "&cOcorreu um erro, chame a staff para reporta este bug."
  #Permissao para os staffers poderem ver as homes dos players.
  Permissao_Staff: "factionmania.check.other"
  Use: "&cUtilize: /home <Home>"
  Teleportado: "&aVocê foi teleportado!"
  Use_1: "&cUtilize /delhome <home>."
  Sem_Home: "&6Homes setadas: &fNenhum"
  Padrao_Setada: "&aHome padrao setada com sucesso."
  Setada: "&ahome '{home}' &acriada com sucesso."
  Deletada: "&aHome '{home}'&a deletada com sucesso."
  Lista: "&6Homes setadas: &f{homes}"
  Permissao_Membro_Limite: "faction.homelimite.membro"
  Max_Home_Membro: 5
  Permissao_Paladino_Limite: "faction.homelimite.paladino"
  Max_Home_Paladino: 10
  Permissao_Guerreiro_Limite: "faction.homelimite.guerreiro"
  Max_Home_Guerreiro: 15
  Permissao_Soberano_Limite: "faction.homelimite.soberano"
  Max_Home_Soberano: 20
  Permissao_Staff_Limite: "factionmania.home.staff"
  Max_Home_Staff: 100
  Alcancou_O_Limite: "&cVoce chegou no limite de homes."
  Permissao_Ignorar_Delay: "factionmania.home.semdelay"
  Aguarde: "&cEm 3 segundos voce ira para sua home."
  Delay: 3