# Plugin criado por iTheG0D_|zLeoDev_
# Meu Skype: dev.leandro
# Meu Twitter: @zLeoDev_
# Duvidas manda msg em alguma dessas opcoes ^^

Configuracao:
   Delay_Entre_Reports: true
   Tempo_Delay: 40

Mensagens:
   Prefix: '&c{!}'
   Enviado: '&aDenuncia enviada com sucesso '
   Erro: '&cOcorreu um Erro, tente novamente '
   Erro_Args: '&cUse /report <jogador> <motivo>'
   Erro_Encontrado: '&cEste jogador nao esta online.'
   Delay: '&cAguarde para enviar outro report .'
   Novo_Report: '&aUma nova denuncia foi feita, para visualiza-la use /reports'
   Staff_Aceita: '&aDenuncia aceita !'
   Staff_Negada: '&cDenuncia negada !'
   Banido: '&cVoce foi banido do servidor!'
   Report_Strings:
   - ' '
   - '{prefix}: &cNovo Report:'
   - ' &7Quem Reportou: &4{reportou}'
   - ' &7Motivo: &4{motivo}'
   - ' &7Reportado: &4{reportado}'
   - ' '