#Login para staff
Staff: true
SMensagem: "&cO staffer [nick] entrou no servidor"
#Login para VIP
#Permisao para setar:  - vip
Vip: true
VMensagem: "&aO jogador [nick] e vip e acabou de entrar no servidor"
#Mensagem de trocar entrou e saiu
#Permisao para setar:  - membro
EMensagem: true
entrou: "&8[nick] acabou de entrar no servidor"
saiu: "&4[nick] acabou de sair do servidor"

