Location1: 'Arenas:-315.69999998807907:5.0:-1127.699999988079:-44.25082:5.5499763:'
Location2: 'Arenas:-309.30000001192093:5.0:-1121.300000011921:-225.00081:4.649976:'
Camarote: 'Arenas:-311.9736705132487:9.0:-1124.366115672339:-91.65115:0.15002634:'
Exit: 'Arenas:-311.9736705132487:9.0:-1124.366115672339:-91.65115:0.15002634:'
DisableCommands: true
CommandsEnable:
- /g
- /l
X1CUSTO: 50000
X1PREMIO: 100000
X1EMPATE: 5000
TimeInvite: 60
TimeDuel: 1200
TimeEND: 30
DCKILL: true
Messages:
  Error: '&b[&3X1&b] &9Use: &b/x1 desafiar [jogador] &9- Para desafiar \n&b[&3X1&b]
    &9Use: &b/x1 aceitar [jogador] &9- Para aceitar \n&b[&3X1&b] &9Use: &b/x1 negar
    [jogador] &9- Para negar \n&b[&3X1&b] &9Use &b/x1 camarote - &9Para ir para o
    camarote \n&b[&3X1&b] &9Use &b/x1 admin &9- Para ver a lista de comandos admin'
  Error2: '&b[&3X1&b] &9Console nao pode usar esse comando'
  Error3: '&b[&3X1&b] &9Esse jogador nao pediu X1 para voce'
  Error4: '&b[&3X1&b] &9Ja possui um pedido de X1 ou uma luta pendente aguarde encerrar
    para usar esse comando'
  Success: '&b[&3X1&b] &9O jogador $1 convidou $2 para um X1 e ele tem $3 segundos
    para aceitar'
  Success2: '&b[&3X1&b] &9$1 aceitou o pedido de X1 de $2 (Para assistir digite /x1
    camarote) (Luta encerra em: $4 segundos)'
  ErrorMoney: '&b[&3X1&b] &9Um dos 2 jogadores nao tem $1'
  Offline: '&b[&3X1&b] &9O jogador esta offline'
  Camarote: '&b[&3X1&b] &9Voce foi teleportado para o camarote'
  ErrorPermission: '&b[&3X1&b] &9Voce nao tem permisao para usar esse comando'
  SetLocationSuccess: '&b[&3X1&b] &9Local setado com sucesso'
  CommandsAdmin: '&b[&3X1&b] &9Use: /x1 admin setloc1 - Para setar o primeiro local
    \n&3[X1] Use: /x1 admin setloc2 - Para setar o segundo lugar \n&3[X1] Use: /x1
    admin setcamarote - Para setar o camarote \n&3[X1] Use: /x1 admin setexit - Para
    setar a saida'
  CommandsError: '&b[&3X1&b] &9Voce nao pode usar esse comando em um X1'
  TimeInvite: '&b[&3X1&b] &9O jogador $1 arregou X1 contra $2'
  TimeDuel: '&b[&3X1&b] &9O X1 de $1 contra $2 foi encerrado pelo TEMPO e foi dado
    $3 para cada'
  DuelStop: '&b[&3X1&b] &9Luta Encerrada'
  Win: '&b[&3X1&b] &9$1 venceu X1 contra $2 e recebeu $3'
  WinDC: '&b[&3X1&b] &9$1 deu DC no X1 e o vencedor foi $2 ganhando $3'
  ErrorPlayer: '&b[&3X1&b] &9Voce nao pode mandar um pedido de X1 para voce mesmo'
  TimeEND: '&b[&3X1&b] &9O vencedor tem $1 segundos para pegar os itens do chao'
  Deny: '&b[&3X1&b] &9O jogador $1 negou x1 contra $2'
