Permissions:
  Admin: 'kAdmin.Command.Admin'
  View: 'kAdmin.View'
  Frozen: 'kAdmin.Command.Frozen'
  Nofall: 'kAdmin.Command.Nofall'
  Cage: 'kAdmin.Command.Cage'
  View: 'kAdmin.Command.View' 
  Report: 'kAdmin.ViewReport' 
  
Messages:
  Admin-Join: '&aVoce entrou No Modo Admin!'
  Admin-Quit: '&aVoce saiu Do Modo Admin!'
  No-Perm: '&cVocê Não Tem Permissão!'
  Caged: '&aVocê Prendeu O Jogador {Preso}'
  Frozen-On: '&aVocê Congelou o Jogador {Congelado}'
  Frozen-Off: '&aVocê Descongelou o Jogador {Congelado}'
  Frozed-On: '&aVocê Foi Congelado Pelo {Staff}'
  Frozed-Off: '&aVocê Foi Descongelado Pelo {Staff}' 
  New-Report: '&aO Jogador &f: {Reporter} &aReportou o Jogador &f {Reportado} &aMotivo &f: {Motivo}'
  Reported: '&aVocê Reportou o Jogador {Reportado} Motivo {Motivo}'
  Inf: '&aInformações Do Jogador &f : &6 {Jogador}'
  Incorrect-Sintax:
    Frozen: '&cSintaxe Incorreta! &aUse &7/&fFrozen &6Jogador.'
    Nofall: '&cSintaxe Incorreta! &aUse &7/&fNofall &6Jogador.'
    Report: '&cSintaxe Incorreta! &aUse &7/&fReport &6Jogador.'
    Cage: '&cSintaxe Incorreta! &aUse &7/&fCage &6Jogador.'
    View: '&cSintaxe Incorreta! &aUse &7/&fView &6Jogador.'
  Invalid-Player: '&cJogador Inválido Ou Offline!'
  Is:
    Force-Field: '&cO Jogador {Hacker} &cEstá Usando Force-Field! Chance &f: {Chance}'
    Nofall: '&cO Jogador {Hacker} &cEstá Usando Nofall!'