# 
# Optional schematic specific configuration
lobby:
  world: SkyWars
  spawn: 151.37 91.00 223.29 181.90 7.80
  radius: 0
score:
  per-kill: 3
  per-win: 10
  on-death: -1
  on-leave: -1
  groups:
    example:
      per-kill: 3
      per-win: 10
      on-death: -1
      on-leave: -1
schematics:
  schematic-name:
    min-players: 2
    timer: 11
  sw1:
    min-players: 8
    timer: 11
  sw2:
    min-players: 1
    timer: 5
  sw3:
    min-players: 1
    timer: 5
statistics:
  update-interval: 600
  top: 30
data-storage: FILE
database:
  hostname: localhost
  port: 3306
  username: username
  password: password
  database: database
islands-per-row: 100
island-buffer: 5
island-building:
  enabled: false
  interval: 1
  blocks-per-tick: 20
build-cages: true
ignore-air: false
fill-empty-chests: true
fill-populated-chests: true
use-economy: false
disable-kits: false
chat-handled-by-other-plugin: false
clear-inventory-on-join: true
save-inventory: true
whitelisted-commands:
- g
- global
- gamemode
