# iConomy 6.0.8b
# @author     Nijikokun <nijikokun@gmail.com>
# @license    GPLv2
# @copyright  Copyright AniGaiku LLC (C) 2010-2011
System:
  Permissions:
    Use:
      Holdings: false
  Default:
    Currency:
      Major:
      - Coins
      - Coins
      Minor:
      - Coins
      - Coins
    Account:
      Holdings: 0.0
  Rank-Size: 5
  Formatting:
    Minor: false
    Seperate: false
    Single: false
  Logging:
    Enabled: true
  Purging:
    Enabled: false
  Interest:
    Enabled: false
    Online: true
    Announce:
      Enabled: false
    Interval:
      Seconds: 90
    Amount:
      Cutoff: 0.0
      Percent: 0.0
      Maximum: 1
      Minimum: 2
  Database:
    Type: minidb
    MajorItem: 266
    MinorItem: 265
    Table: iConomy
    URL: mysql://localhost:3306/iConomy
    Username: root
    Password: ''
    Conversion:
      Enabled: false
      Type: H2DB
      Table: iConomy
      URL: mysql://localhost:3306
      Username: root
      Password: ''
      All: true
Rank-Size: 5
