# Enable debug info in console
debug-mode: false

# Enable colors in console output
color-logs: true

# Enable sounds
# All compatible sounds can be found in this list: http://jd.bukkit.org/rb/apidocs/org/bukkit/Sound.html
play-sounds: true

# Sound played at both gates when teleporting
teleport-sound: SPLASH

# Sound played at gates when activated (fills with water)
activate-sound: SWIM

# Sound played when selecting a destination
destination-sound: FIRE_IGNITE

# The tag for line 1 on the gate signs. Default is 'gate'.
gate-sign-tag: 'gate'

# Enable or disable the use of remote gate signs
enable-remote-signs: true

# The tag for line 1 on the remote signs. Default is 'remote'.
remote-sign-tag: 'remote'

# The style for gate names. Maximum of 4 characters. Anything longer will be cut off.
# Note: Bug in Minecraft requires color codes to come BEFORE style codes or the style will not work.
gate-name-style: '&1&l'

# The style for destination names. Maximum of 2 characters. Anything longer will be cut off.
# Note: Bug in Minecraft requires color codes to come BEFORE style codes or the style will not work.
gate-destination-style: '&o'

# Maximum number of frame blocks allowed per gate
maximum-frame-blocks: 25

# Teleport minecarts through gates
teleport-minecarts: true

# Enable or disable filler effect for "always on" gates
always-on-show-filler: true

# The default filler if none specified on sign
default-filler: STATIONARY_WATER

# Allow buttons to activate/deactivate gates
use-buttons: true

# Number of seconds for gates to stay active when button its pressed
remain-active-for: 10

# Allowed materials for gate frames
frame-materials:
- STONE
- WOOD
- OBSIDIAN
- IRON_BLOCK
- QUARTZ_BLOCK
- LAPIS_BLOCK
- REDSTONE_BLOCK