# 
# +------------------------------------------------------+ #
# |                     Server MOTD                      | #
# |                     Version 2.2                      | #
# +------------------------------------------------------+ #
JoinGame MOTD: {}
Server MOTD: "&4Manuten\xe7\xe3o "
