# For further instruction,
# see dev.bukkit.org/server-mods/more-sounds
#                                             .
# Sounds format: name, pitch, volume
#                                             .
sounds:
  join: note-pling
  leave: note-bass
  chat: item-pickup, 1.9
  command: item-pickup, 1.9
  hit: hurt-flesh, 1.8
  hit-sword: hurt-flesh, 1.8
  hit-arrow: orb-pickup, 1.2, 5.0
  teleport: portal-travel, 2.0
  on-death: wither-spawn
  hotbar-scroll: note-sticks, 1.1, 0.5
  inventory-click: note-sticks, 1.1, 0.5
update-notifications: true
teleport-particles: true
