################################################	
#Plugin feito por Lucca R.                     #
#Favor nao retirar os creditos                 #
#Acesse nosso servidor: enderkits.tintahost.com#
################################################

#Este é o prefixo que ira aparecer quando voce reportar um jogador

ReportSucess: "&b[EnderKits] &cJogador reportado com sucesso se houver Staff online verao seu report!"