#######################################################
##                   Created By                      ##
##                    Deckerz                        ##
#######################################################
announcement:
    enabled: true
    random: false
    prefix: '&r[&aSeu&fServidor&r] '
    interval: 30
    check-for-updates: true
    auto-update: false
    messages:
    - '&f Ola [player], temos [online] pessoas online neste momento.'
    - '&c[player] &fConfira nossos Planos Vip '
    - '&c[player] &avote no servidor e ganhe itens digite &9/vote &apara saber onde votar'
    - '&c[player] &9 para quebrar Obsidian exploda 4 TNTs, Bedrock exploda 15 TNTs'
    - '&9 Para criar uma Fac digite &a/f create NOMEDAFAC'
    - '&f Use uma batata para saber a durabilidade da Obsidian e da Bedrock'
    - '&eServidor em fase Beta'
 
