# Tablist v1.3.1.11 by sn1cko
# Time is set in milliseconds which means every 20 = 1 second
# for example: 6000 = 5 minuntes OR 300 = 15 seconds
# 
# The announcer will never stop if the time is set to 0
# Else it will stop after the amount of milliseconds you wish
# 
# There are currently 15 variables available which can be built in
# for example %player% - will display the playername or %health% - will give out the health
# all other variables can be found on the website
# http://dev.bukkit.org/bukkit-plugins/tablist/pages/variables
Tablist:
  Settings:
    Staff:
      Permission: tablist.staff
    ShowVanishedPlayerOnVariable:
      Toggle: false
      ChangeText:
        Toggle: false
        UsersSeeOnlineText: '%online%'
        StaffsSeeOnlineText: '%online% | %vanished%'
    Toggle: false
    Time: 50
    Messages:
      Header:
      - '&e&lSEUSERVER  '
      Footer:
      - |2-


        &e&lBem Vindo

        &7 Servidor configurado por Luuc4s!!
