#  Este plugin foi desenvolvido por gabrielAlves todos direitos reservados '-'
#  Nao vendam falando que e seu pq e feio :D
#  Qualquer duvida chama skyp Facebook:Cassimaro.ca

Seguranca:
  SERIAL_SERVIDOR: 'KWI9-FAM2-AWF8-KSA4'
  SERIAL_NOME_SERVIDOR: 'GabrielAlves'
